@_4Manager.API_HostAddress = http://localhost:5083
@AccessToken = eyJhbGciOiJIUzI1NiIsImtpZCI6IkJjYjIxOWRkcTM2MUMydWIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3ZsdWduZ2xlZG15amNkdWxyemxqLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2OTBjOWZjMi04ZmFmLTRjOWQtOTUwNy00MjIyZDMxNGYyNTgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYyMzYwMzc2LCJpYXQiOjE3NjIzNTY3NzYsImVtYWlsIjoiYnJlbmRhcGlsZXRAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NjIzNTY3NzZ9XSwic2Vzc2lvbl9pZCI6ImFiMzlhOGNlLTZmODQtNDZhMC1iZmU5LTA3NWY5MjNjMWM3NCIsImlzX2Fub255bW91cyI6ZmFsc2V9.dfmWGXeaFMQLQbVjvJoaKtwMc4M6dAXH6QrNNNrcxb0

GET {{_4Manager.API_HostAddress}}/api/v1/user/
Accept: application/json
Authorization: Bearer {{AccessToken}}
###
