@_4Manager.API_HostAddress = http://localhost:5083
@AccessToken = eyJhbGciOiJIUzI1NiIsImtpZCI6IlY1cWFoYnNIVjlJMzVJK04iLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2x4cGpieHNxbXhnenFmeW13cHJmLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIxODJjNGM3ZS0xZmZlLTQ2NjAtYTFhNC0zYmJhZDQyMmZhNGUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU0NDUwNDc5LCJpYXQiOjE3NTQ0NDY4NzksImVtYWlsIjoiYnJlbmRhcGlsZXRAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImJyZW5kYXBpbGV0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6IjE4MmM0YzdlLTFmZmUtNDY2MC1hMWE0LTNiYmFkNDIyZmE0ZSJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzU0NDQ2ODc5fV0sInNlc3Npb25faWQiOiIyMzc4MjM0MS05MDBlLTQwNGEtYWM4ZS1mMTU5ZjEyNzIyODEiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.EAaw_9b2F8D-E2s1Yl4t2NkLkta0Zv862r2UaxPCKBg

PUT {{_4Manager.API_HostAddress}}/usuarios/atualizar-perfil
Accept: application/json
Authorization: Bearer {{AccessToken}}
###
