// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _4Manager.Persistence.Context;

#nullable disable

namespace _4Tech._4Manager.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251229142309_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.MessageHistory", b =>
                {
                    b.Property<Guid>("MessageHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TicketDetailsId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageHistoryId");

                    b.HasIndex("TicketDetailsId");

                    b.ToTable("messageHistory", (string)null);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TicketDetailsId")
                        .HasColumnType("uuid");

                    b.HasKey("NoteId");

                    b.HasIndex("TicketDetailsId");

                    b.ToTable("note", (string)null);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerManagerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Favorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusProject")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StatusTime")
                        .HasMaxLength(50)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TitleColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerManagerId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.TeamCollaborator", b =>
                {
                    b.Property<Guid>("TeamCollaboratorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamCollaboratorId");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("TeamId");

                    b.ToTable("team_collaborators", (string)null);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Applicant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DeadlineDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InternalCall")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponsibleArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TicketResponsible")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TicketStatus")
                        .HasColumnType("integer");

                    b.HasKey("TicketId");

                    b.HasIndex("ProjectId");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.TicketAttachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AttachmentId");

                    b.HasIndex("TicketId");

                    b.ToTable("ticketAttachment", (string)null);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.TicketDetails", b =>
                {
                    b.Property<Guid>("TicketDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("TicketDetailsId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("ticketDetails", (string)null);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Timesheet", b =>
                {
                    b.Property<Guid>("TimesheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlockColor")
                        .HasColumnType("text");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TimesheetId");

                    b.HasIndex("UserId");

                    b.ToTable("timesheets", (string)null);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcessLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserProfilePicture")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.MessageHistory", b =>
                {
                    b.HasOne("_4Tech._4Manager.Domain.Entities.TicketDetails", null)
                        .WithMany("MessageHistory")
                        .HasForeignKey("TicketDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Note", b =>
                {
                    b.HasOne("_4Tech._4Manager.Domain.Entities.TicketDetails", null)
                        .WithMany("Note")
                        .HasForeignKey("TicketDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Project", b =>
                {
                    b.HasOne("_4Tech._4Manager.Domain.Entities.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("_4Tech._4Manager.Domain.Entities.UserProfile", "CustomerManager")
                        .WithMany()
                        .HasForeignKey("CustomerManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("CustomerManager");
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Team", b =>
                {
                    b.HasOne("_4Tech._4Manager.Domain.Entities.UserProfile", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_4Tech._4Manager.Domain.Entities.Project", "Project")
                        .WithOne("Team")
                        .HasForeignKey("_4Tech._4Manager.Domain.Entities.Team", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.TeamCollaborator", b =>
                {
                    b.HasOne("_4Tech._4Manager.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("TeamCollaborators")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4Tech._4Manager.Domain.Entities.Team", "Team")
                        .WithMany("Collaborators")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("_4Tech._4Manager.Domain.Entities.Project", "Project")
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.TicketAttachment", b =>
                {
                    b.HasOne("_4Tech._4Manager.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.TicketDetails", b =>
                {
                    b.HasOne("_4Tech._4Manager.Domain.Entities.Ticket", "Ticket")
                        .WithOne("TicketDetails")
                        .HasForeignKey("_4Tech._4Manager.Domain.Entities.TicketDetails", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Timesheet", b =>
                {
                    b.HasOne("_4Tech._4Manager.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Project", b =>
                {
                    b.Navigation("Team")
                        .IsRequired();

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Team", b =>
                {
                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("TicketDetails");
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.TicketDetails", b =>
                {
                    b.Navigation("MessageHistory");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("_4Tech._4Manager.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("TeamCollaborators");
                });
#pragma warning restore 612, 618
        }
    }
}
