name: Trigger auto deployment for api-4manage

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:    

jobs:
  # ==========================================
  # CAIXA 1: TESTES (CI)
  # ==========================================
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Rodar Testes de Unidade (Application Layer)
        run: dotnet test tests/4Manager.Application.Tests/ --configuration Release

  # ==========================================
  # CAIXA 2: BUILD E DEPLOY (CD)
  # ==========================================
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test # <-- ISSO AQUI CRIA A LINHA LIGANDO AS DUAS CAIXINHAS!
    environment: production
    permissions: 
      id-token: write 
      contents: read 

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.API4MANAGE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.API4MANAGE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.API4MANAGE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./src/4Manager.API/Dockerfile
          registryUrl: acrteste4managerapi-a6bqbxfghye5gbcr.azurecr.io
          registryUsername: ${{ secrets.API4MANAGE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.API4MANAGE_REGISTRY_PASSWORD }}
          containerAppName: api-4manage
          resourceGroup: rg-4manage
          imageToBuild: acrteste4managerapi-a6bqbxfghye5gbcr.azurecr.io/api-4manage:${{ github.sha }}
          targetPort: 8080
          containerAppExists: true
